name: Rozmarin Cafe
favicon: null
layout_spectrum: 0.99778
typography_spectrum: 0.65852
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A0C8B0'
    - '#282008'
    - '#A09058'
    - '#988040'
    - '#D0C088'
  brandStrength: 0.383118
  lightness: 0.728482
  saturation: 0.856624
  rhythmicContrast: 0.050823
purpose:
  - name: null
    item: null
    url: null
